version: '2.1'
services:
  db:
    container_name: db
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    container_name: app
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - "9043:9043"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b

volumes:
  db-data:
  pgadmin-data: