server:
  port: 9042

spring:
  # Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    default-schema: public
    enabled: true
    drop-first: false
    password: secret
    user: admin